# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FIRM_res <- function(SS2, hvg_ind_SS2, SS2_FindClusters, tenx, hvg_ind_tenx, tenx_FindClusters, dims, gene_all_num, gene_all_hvg_ind, gene_all_ind_SS2, gene_all_ind_tenx, dataset_list, quantile_default, rept_ds = 50L, k = 5L, max_k = 300L) {
    .Call('_FIRM_FIRM_res', PACKAGE = 'FIRM', SS2, hvg_ind_SS2, SS2_FindClusters, tenx, hvg_ind_tenx, tenx_FindClusters, dims, gene_all_num, gene_all_hvg_ind, gene_all_ind_SS2, gene_all_ind_tenx, dataset_list, quantile_default, rept_ds, k, max_k)
}

FIRM_res_all <- function(SS2, hvg_ind_SS2, SS2_FindClusters, tenx, hvg_ind_tenx, tenx_FindClusters, dims, gene_all_num, gene_all_hvg_ind, gene_all_ind_SS2, gene_all_ind_tenx, dataset_list, quantile_default, rept_ds = 50L, k = 5L, max_k = 300L, coreNum = 1L) {
    .Call('_FIRM_FIRM_res_all', PACKAGE = 'FIRM', SS2, hvg_ind_SS2, SS2_FindClusters, tenx, hvg_ind_tenx, tenx_FindClusters, dims, gene_all_num, gene_all_hvg_ind, gene_all_ind_SS2, gene_all_ind_tenx, dataset_list, quantile_default, rept_ds, k, max_k, coreNum)
}

